### ISSUE TITLE
Condition never ran

### ISSUE THREAD

**Issue by indiejoseph** [carpedm20/lstm-char-cnn-tensorflow#4]
Line 159 in batch_loader.py

```
if len(char) == max_word_length:
  chars[-1] = char2idx['}']
```

**Comment by carpedm20** [comment]
That's because we set the max_word_length pretty large number which is `64`. I remember that the longest word length in ptb dataset was around forty so this might not be a problem.

**Comment by carpedm20** [comment]
Let's check and close this issue again.

**Comment by indiejoseph** [comment]
But the length of `char` is away 1, i think you attempt to check the length of `chars` instead.

**Comment by carpedm20** [comment]
@indiejoseph Thanks!

**Comment by indiejoseph** [comment]
@carpedm20 And it should place before:

```
for idx in xrange(min(len(chars), max_word_length)):
  output_char[word_num][idx] = chars[idx]
```

Isn't it?

**Comment by carpedm20** [comment]
@indiejoseph I think you are right but the original code has a same order https://github.com/yoonkim/lstm-char-cnn/blob/master/util/BatchLoaderUnk.lua#L185. @yoonkim should see this I guess because if

```
if len(char) == max_word_length:
  chars[-1] = char2idx['}']
```

is in below, it will have no affect to the code. But this is not a critical problem because the max_word_length is big enough and this code will not be executed in `ptb` dataset.
